### ISSUE TITLE
Application not work on SCP Cloud Foundry env

### ISSUE THREAD

**Issue by fableh** [SAP/iot-application-services-sdk-nodejs#4]
Hi all,

i´ve just tried this litte node js application to run this on scp cloud foundry.
I got the following errors (see attachement).
The main problem is mainly to fetch the host (internal SAP host ???)

>> http://nexus.wdf.sap.corp:8081

My setup is the following:

package.json:

```
{
  "name": "scp_iot_proxy",
  "version": "1.0.2",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "iot-application-services-sdk-nodejs": "https://github.com/SAP/iot-application-services-sdk-nodejs"
  },
  "author": "",
  "license": "ISC"
}
```
manifest.yaml

```
---
applications:
- name: scp_iot_proxy
  buildpack: nodejs_buildpack
  command: node index.js
  memory: 128M
  disk_quota: 128M
  host: scp_iot_proxy
```

[error.txt](https://github.com/SAP/iot-application-services-sdk-nodejs/files/1651883/error.txt)

thx and br,
fabian
